### ISSUE TITLE
Time abstraction functions

### ISSUE THREAD

**Issue by JamesWooldridge** [JamesWooldridge/csse7032-a1#1]
We need some functions that allow us to abstract the calculation of time. This is so we can determine whether two legs are within 3 1/2 hours of each other.

**Comment by DanielMcInnes** [comment]
I just started on them.

**Comment by DanielMcInnes** [comment]
I added start\_time to the journey schema. Should I add constraints to describe that legs can only be added to a journey within 3.5 hours?

**Comment by JamesWooldridge** [comment]
That would be great!

**Comment by DanielMcInnes** [comment]
Ready for review please!

also, can I replace:

\t1		b.legs = a.legs \cat \langle l \rangle	 \land\\
\t1		journeys' = journeys \oplus \{(\#journeys, b)\} \land\\

with:

                 a'.legs = a.legs \cat \langle l \rangle

?

**Comment by JamesWooldridge** [comment]
We can't specify the prime state of the variable in the Journey schema unfortunately, so we have to essentially 'recreate' it and put it back into the sequence within the GoCard schema (thus using 'b'). Check out the thread called 'Copying an instantiation of a schema' on the course discussion board for more details from Graeme.
